# Site settings
title: Brainstem Brewing Taplist
email: your-email@domain.com
description: Slick Material Design theme for Jekyll powered by Material Design Lite.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
copyright: '&copy; 2015-2016 Smart Material Theme'

# Build settings
markdown: kramdown

# Custom theme could be generated at: https://getmdl.io/customize/index.html
material_theme: blue-deep_orange

# Google Analytics account ID (UA-XXXXXXXX-X)

google-analytics-ua: UA-84475574-1
